### ISSUE TITLE
CELERY_TASK_RETRY_KWARGS may not be required if SEND_EMAIL is False

### ISSUE THREAD

**Issue by efe** [Hipo/django-ses-plus#4]
`settings.py`:
```
EMAIL_BACKEND = 'django_ses_plus.backends.SESPlusBackend'
DJANGO_SES_PLUS_SETTINGS = {
    "SEND_EMAIL": False,
}
```

Traceback:
```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/django_ses_plus/models.py", line 10, in <module>
    from django_ses_plus.settings import DJANGO_SES_PLUS_SETTINGS
  File "/usr/local/lib/python3.7/site-packages/django_ses_plus/settings.py", line 6, in <module>
    DJANGO_SES_PLUS_SETTINGS["CELERY_TASK_RETRY_KWARGS"].setdefault("CELERY_TASK_RETRY_KWARGS", {'max_retries': 15, 'countdown': 60})
KeyError: 'CELERY_TASK_RETRY_KWARGS'
```

**Comment by alicertel** [comment]
@omerfarukabaci Could you please check this issue when you have time?

**Comment by alicertel** [comment]
Solved with the latest release
